#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER IF NOT EXISTS ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
    ALTER USER ${POSTGRES_USER} CREATEDB;
    CREATE DATABASE ${POSTGRES_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
EOSQL